export enum LeadStatus {
    NEW = "NEW",
    UNDER_REVIEW = "UNDER_REVIEW",
    CONTACTED = "CONTACTED",
    COUNSELLING_SCHEDULED = "COUNSELLING_SCHEDULED",
    COUNSELLING_COMPLETED = "COUNSELLING_COMPLETED",
    FOLLOWUP_REQUIRED = "FOLLOWUP_REQUIRED",
    INTERESTED = "INTERESTED",
    NOT_INTERESTED = "NOT_INTERESTED",
    ON_HOLD = "ON_HOLD",
    CLOSED = "CLOSED",
    CONVERTED = "CONVERTED"
}

export enum ApplicationStatus {
    PENDING = "PENDING",
    SUBMITTED = "SUBMITTED",
    APPLIED = "APPLIED",
    FINALIZED = "FINALIZED",
    UNDER_REVIEW = "UNDER_REVIEW",
    OFFER_RECEIVED = "OFFER_RECEIVED",
    READY_FOR_VISA = "READY_FOR_VISA",
    VISA_PROCESS = "VISA_PROCESS",
    ENROLLED = "ENROLLED",
    DEFERRED = "DEFERRED",
    REJECTED = "REJECTED",
    WITHDRAWN = "WITHDRAWN"
}

export enum VisaType {
    STUDENT_VISA = "STUDENT_VISA",
    DEPENDENT_VISA = "DEPENDENT_VISA",
    WORK_VISA = "WORK_VISA",
    TOURIST_VISA = "TOURIST_VISA"
}

export enum VisaStatus {
    VISA_GUIDANCE_GIVEN = "VISA_GUIDANCE_GIVEN",
    DOCUMENTS_CHECKLIST_SHARED = "DOCUMENTS_CHECKLIST_SHARED",
    DOCUMENTS_PENDING = "DOCUMENTS_PENDING",
    DOCUMENTS_RECEIVED = "DOCUMENTS_RECEIVED",
    DOCUMENTS_VERIFIED = "DOCUMENTS_VERIFIED",
    FINANCIAL_DOCUMENTS_PENDING = "FINANCIAL_DOCUMENTS_PENDING",
    SPONSORSHIP_DOCUMENTS_PENDING = "SPONSORSHIP_DOCUMENTS_PENDING",
    VISA_APPLICATION_IN_PROGRESS = "VISA_APPLICATION_IN_PROGRESS",
    VISA_APPLICATION_SUBMITTED = "VISA_APPLICATION_SUBMITTED",
    BIOMETRICS_SCHEDULED = "BIOMETRICS_SCHEDULED",
    BIOMETRICS_COMPLETED = "BIOMETRICS_COMPLETED",
    UNDER_REVIEW = "UNDER_REVIEW",
    ADDITIONAL_DOCUMENTS_REQUESTED = "ADDITIONAL_DOCUMENTS_REQUESTED",
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
    VISA_APPROVED = "VISA_APPROVED",
    VISA_GRANTED = "VISA_GRANTED",
    VISA_REFUSED = "VISA_REFUSED",
    VISA_REJECTED = "VISA_REJECTED",
    VISA_WITHDRAWN = "VISA_WITHDRAWN",
    DEFERRED = "DEFERRED",
    ENROLLED = "ENROLLED",
    PENDING = "PENDING"
}

export enum StudentStatus {
    NEW = "NEW",
    UNDER_REVIEW = "UNDER_REVIEW",
    COUNSELLING_COMPLETED = "COUNSELLING_COMPLETED",
    COUNSELLING_SCHEDULED = "COUNSELLING_SCHEDULED",
    DOCUMENT_PENDING = "DOCUMENT_PENDING",
    DOCUMENT_VERIFIED = "DOCUMENT_VERIFIED",
    INTERESTED = "INTERESTED",
    NOT_INTERESTED = "NOT_INTERESTED",
    NOT_ELIGIBLE = "NOT_ELIGIBLE",
    ON_HOLD = "ON_HOLD",
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
}

export enum LeadTemperature {
    HOT = "HOT",
    WARM = "WARM",
    COLD = "COLD"
}
